[package]
name = "nyat-core"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
error_set = { workspace = true }
smallvec = { workspace = true }
socket2 = { workspace = true }
stun = { workspace = true }
thiserror = "2.0.18"
tokio = { workspace = true }
url.workspace = true
