name: release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux (musl, static)
          - { target: x86_64-unknown-linux-musl,        os: ubuntu-latest }
          - { target: aarch64-unknown-linux-musl,       os: ubuntu-latest }
          - { target: armv7-unknown-linux-musleabihf,   os: ubuntu-latest }
          - { target: arm-unknown-linux-musleabihf,     os: ubuntu-latest }
          - { target: i686-unknown-linux-musl,          os: ubuntu-latest }
          - { target: riscv64gc-unknown-linux-musl,     os: ubuntu-latest }
          - { target: powerpc64le-unknown-linux-musl,   os: ubuntu-latest }
          # Linux (gnu)
          - { target: x86_64-unknown-linux-gnu,         os: ubuntu-latest }
          - { target: aarch64-unknown-linux-gnu,        os: ubuntu-latest }
          - { target: loongarch64-unknown-linux-gnu,    os: ubuntu-latest }
          - { target: s390x-unknown-linux-gnu,          os: ubuntu-latest }
          - { target: powerpc64-unknown-linux-gnu,      os: ubuntu-latest }
          # macOS
          - { target: aarch64-apple-darwin,             os: macos-latest }
          - { target: x86_64-apple-darwin,              os: macos-latest }
          # FreeBSD
          - { target: x86_64-unknown-freebsd,           os: ubuntu-latest }
          # Windows
          - { target: x86_64-pc-windows-msvc,           os: windows-latest }
          - { target: aarch64-pc-windows-msvc,          os: windows-latest }
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: -Zunstable-options -Cpanic=immediate-abort
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rust-src
      - run: mkdir -p .cargo && printf '[unstable]\nbuild-std = ["std"]\n' > .cargo/config.toml
        shell: bash
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: runner.os == 'Linux'
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: nyat
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          include: LICENSE,nyat/README.md,nyat/nyat.toml
          token: ${{ secrets.GITHUB_TOKEN }}
